#!/bin/sh

outname=productiveDrt
rm -f $outname
./c2macro.pl blitzDrt.c++ >sourcecode.h

g++ -o $outname -O3 -march=native -mtune=native blitzDrt.c++ -Wall -Wextra -lfftw3 -lboost_program_options `pkg-config --cflags --libs Magick++`

strip $outname

